spring.application.name=artbook-dao

spring.datasource.password=vmX1MKHhnmLDayQnDFreM8sUEvoG8gZT
spring.datasource.url=jdbc:postgresql://dpg-d5sm5r4r85hc73dm62v0-a:5432/artbook_t6bd
spring.datasource.username=artbook_admin

app.location.config=/bucket/config
app.location.storage=/bucket/storage

health.verify.fail-hard=false