spring.application.name=artbook-dao

app.location.config=/bucket/config
app.location.storage=/bucket/storage

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=8oMpwrFCDDGOZcLBMC2aNUt8dY7657aw
spring.datasource.url=jdbc:postgresql://dpg-d5un2ishg0os73b1kn20-a:5432/artbook_dalh
spring.datasource.username=artbook_admin

# optional
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true