spring.application.name=artbook-dao

app.location.config=/bucket/config
app.location.storage=/bucket/storage

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=OdWdXBcGCvUTBpN5dSq8SZKPcN8ncnJy
spring.datasource.url=jdbc:postgresql://dpg-d5unb87pm1nc73c0j00g-a:5432/artbook_y3u2
spring.datasource.username=artbook_y3u2_user

# optional
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true