CREATE TABLE images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uri TEXT NOT NULL UNIQUE,
    properties JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE users_to_images (
    user_id BIGINT NOT NULL,
    image_id BIGINT NOT NULL,
    primary key (user_id, image_id),
    constraint fk_users_to_images_user foreign key (user_id) references users(id) on delete cascade,
    constraint fk_users_to_images_image foreign key (image_id) references images(id) on delete cascade
);